{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rhbk
  annotations:
    haproxy.router.openshift.io/hsts_header: ''
spec:
  host: {{ .Values.route.hostname }}
  to:
    kind: Service
    name: rhbk
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
